config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  post 'transfers/send_money'
  get 'transfers/home'

  resources :users, only: %i[create new]
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :sent_transactions, class_name: 'Transaction', as: :from
  has_many :received_transactions, class_name: 'Transaction', as: :to

  delegate :name, to: :user

  def balance
    sent = sent_transactions.pluck(:amount).reduce(0, :+)
    received = received_transactions.pluck(:amount).reduce(0, :+)

    received - sent
  end

  def add_credit(amount, from = 'Major Bank')
    creditor = Creditor.find_or_create_by(name: from)
    Transaction.create(amount: amount, from: creditor, to: self, created_at: DateTime.now)
  end

  def remove_credit(amount, to = 'Humble Bundle')
    debitor = Debitor.find_or_create_by(name: to)
    Transaction.create(amount: amount, to: debitor, from: self, created_at: DateTime.now)
  end

  def self.transfer(amount, from:, to:)
    raise ArgumentError unless from && to

    Transaction.create(amount: amount, from: from, to: to)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/creditor.rb
# Represents money sources, income from job, bank credits, credit notes.. etc
class Creditor < ApplicationRecord
  has_many :transactions, as: :from

  validates_presence_of :name

  # Creditors have infinite balance for this example's sake.
  def balance
    Float::INFINITY
  end
end

app/models/debitor.rb
# Represents money sinks, food, rent, ram, and partying!
class Debitor < ApplicationRecord
  has_many :transactions, as: :to

  validates_presence_of :name
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :from, polymorphic: true
  belongs_to :to, polymorphic: true

  validates_numericality_of :amount, greater_than: 0, less_than: BigDecimal(10e8, 2)

  validate :source_has_enough_balance, if: -> { from.present? }

  before_validation :ensure_only_two_digits

  def ensure_only_two_digits
    self.amount = BigDecimal(amount, 2)
  end

  def source_has_enough_balance
    raise NotImplementedError unless from.respond_to?(:balance)

    errors.add :amount, 'Source has insufficient balance' unless from.balance >= amount
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :account

  validates_presence_of :first_name, :last_name, :password_digest, :email
  validates :email, uniqueness: true, format: URI::MailTo::EMAIL_REGEXP

  delegate :balance, :sent_transactions, :received_transactions, to: :account

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def current_user
    return false unless session[:current_user_id]

    @current_user ||= User.find(session[:current_user_id])
  rescue ActiveRecord::RecordNotFound
    false
  end

  def authorize!
    redirect_to login_path unless current_user
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to root_path, notice: 'You are already signed in' if current_user.present?
  end

  def create
    user = User.find_by_email(session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:current_user_id] = user.id
      redirect_to root_path, notice: "Welcome #{user.last_name}, #{user.first_name}"
    else
      redirect_to login_path, alert: "Woah.. that's not the correct stuff buddy"
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authorize!

  def home
    @received_txs = current_user.received_transactions
    @sent_txs = current_user.sent_transactions
    @debitors = Debitor.all
    @friends = User.all.to_a - [current_user]
  end

  def send_money
    tx = Transaction.new(transfer_params)
    if tx.save
      redirect_to root_path, notice: 'Sent Successfully'
    else
      redirect_to root_path, alert: 'Something went wrong!'
    end
  end

  private

  def transfer_params
    params.require(:transaction).permit(:from_type, :to_type, :from_id, :to_id, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    return redirect_to :new, alert: "Please Confirm Your Password!" unless password_confirmed?

    @user = User.new(user_params.except(:password_confirm))
    return redirect_to :new, alert: "Fill in everything please" unless @user.valid?

    @user.save
    @user.build_account.save
    @user.account.add_credit(100, 'ZELL BANK')

    redirect_to root_path, notice: 'Account Created!'
  end

  private

  def password_confirmed?
    params[:user][:password] == params[:user][:password_confirm]
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirm)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if !current_user %>
<div class="container mx-8">
  <div class="box has-background-primary has-text-centered">
    <h3 class="subtitle has-text-dark">Features</h3>
    <p>Free 100$ Credit as soon as you open an account</p>
    <p>Send money to anybody anywhere (as long as they have an account here!)</p>
    <p>See a history of your sent and received cash moneys!</p>
  </div>

  <div class="mx-6 box has-background-primary-light  has-text-centered">
    <p class="subtitle has-text-dark">What are you waiting for?</p>
    <%= link_to 'Create Your Account', new_user_path, { class: 'button is-warning' } %>
    <%= link_to 'Sign In', login_path, { class: 'button is-ghost' } %>
  </div>
</div>
<% else %>
  <div class="container mx-8">
    <div class="box has-background-primary has-text-centered">
      <h3 class="title has-text-dark">Your Balance is <%= current_user.balance %> $</h3>
    </div>

    <div class="buttons is-centered">
      <%= link_to 'Send money to your friends!', transfers_home_path , { class: 'button is-primary'} %>
      <%= link_to  'Pay yo bills!', transfers_home_path, { class: 'button is-warning'} %>
    </div>

  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/main_menu' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if alert %>
  <article class="message is-warning">
    <div class="message-header">
      <p>Nice!</p>
    </div>
    <div class="message-body">
      <%= alert %>
    </div>
  </article>
<% elsif notice %>
  <article class="message is-primary">
    <div class="message-header">
      <p>Whoops</p>
    </div>
    <div class="message-body">
      <%= notice %>
    </div>
  </article>
<% end %>

app/views/shared/_main_menu.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      ZELLBANK
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to 'Home', root_path, class: 'navbar-item' %>

      <% if current_user %>
        <%= link_to 'Send Money', transfers_home_path, {class: 'navbar-item'} %>
      <% end %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if current_user %>
            <%= link_to 'Sign Out', logout_path, class: 'button is-primary' %>
          <% else %>
            <%= link_to 'Sign Up', new_user_path, class: 'button is-primary' %>
            <%= link_to 'Sign In', login_path, class: 'button is-light' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/transfers/home.html.erb
<div class="container mx-6">
  <div class="box has-background-primary has-text-centered">
    <h3 class="subtitle has-text-dark">Your Balance is <%= current_user.balance %> $</h3>
  </div>

  <div class="columns">
    <div class="column">
      <h1 class="subtitle">Send Money</h1>
      <table class="table">
        <tr>
        <th colspan="2">Your Friend</th>
        <th>Amount</th>
        <th></th>
        </tr>
        <% @friends.each do |friend| %>
          <%= form_for :transaction, url: transfers_send_money_url, method: :post do |f| %>
            <%= f.hidden_field :from_id, value: current_user.account.id %>
            <%= f.hidden_field :from_type, value: 'Account' %>
            <%= f.hidden_field :to_type, value: 'Account' %>
            <%= f.hidden_field :to_id, value: friend.account.id %>
            <tr>
              <td><%= friend.first_name %></td>
              <td><%= friend.last_name %></td>
              <td><%= f.number_field :amount, {class: 'input', required: true, min: 1, max: current_user.balance }%></td>
              <td><%= f.submit 'Send', {class: 'button'}%></td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
    <div class="column">
      <h1 class="subtitle">Pay Bills</h1>
      <table class="table">
        <tr>
        <th colspan="1">Your Bill</th>
        <th>Amount</th>
        <th></th>
        </tr>
        <% @debitors.each do |debitor| %>
          <%= form_for :transaction, url: transfers_send_money_url, method: :post do |f| %>
            <%= f.hidden_field :from_id, value: current_user.account.id %>
            <%= f.hidden_field :from_type, value: 'Account' %>
            <%= f.hidden_field :to_type, value: 'Debitor' %>
            <%= f.hidden_field :to_id, value: debitor.id %>
            <tr>
              <td><%= debitor.name %></td>
              <td><%= f.number_field :amount, {class: 'input', required: true, min: 1, max: current_user.balance }%></td>
              <td><%= f.submit 'Pay', {class: 'button'}%></td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <h1 class="subtitle">List of Incomes</h1>
      <table class="table">
        <tr>
          <th>Your Incomes</th>
          <th>Amount</th>
        </tr>
        <% @received_txs.each do |tx| %>
          <tr>
            <td><%= tx.from.name %></td>
            <td><%= tx.amount %><td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="column">
      <h1 class="subtitle">List of Expenses</h1>
      <table class="table">
        <tr>
          <th>Your Expenses</th>
          <th>Amount</th>
        </tr>
        <% @sent_txs.each do |tx| %>
          <tr>
            <td><%= tx.to.name %></td>
            <td><%= tx.amount %><td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="title">Create an Account</h1>

<div class="box mx-7">
  <%= form_for @user, method: :post, url: '/users' do |f| %>
    <div class="field">
      <%= f.label :first_name, {class: 'label'} %>
      <%= f.text_field :first_name,  {class: 'input', required: true} %>
    </div>

    <div class="field">
      <%= f.label :last_name, {class: 'label'} %>
      <%= f.text_field :last_name, {class: 'input', required: true} %>
    </div>

    <div class="field">
      <%= f.label :email, {class: 'label'} %>
      <%= f.email_field :email, {class: 'input', required: true} %>
    </div>

    <div class="field">
      <%= f.label :password, {class: 'label'} %>
      <%= f.password_field :password, {class: 'input', required: true, minlength: 12} %>
    </div>

    <div class="field">
      <%= f.label :password_confirm, {class: 'label'} %>
      <%= f.password_field :password_confirm, {class: 'input', required: true, minlength: 12} %>
    </div>

    <%= f.submit 'Create Account', {class: 'button is-primary is-fullwidth'} %>
  <% end %>
</div>